# Generated by Django 4.2.4 on 2024-01-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataSalud',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_maquina', models.CharField(max_length=50)),
                ('id_empresa', models.CharField(max_length=50)),
                ('f_leidacampo', models.DateField()),
                ('h_leidacampo', models.TimeField(null=True)),
                ('f_enviadanube', models.DateField(null=True)),
                ('h_enviadanube', models.TimeField(null=True)),
                ('id_parametro', models.CharField(max_length=50)),
                ('valor_parametro', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Historial',
            },
        ),
    ]
