# Generated by Django 4.2.4 on 2024-01-24 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vistaTablas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasalud',
            name='f_enviadanube',
        ),
        migrations.RemoveField(
            model_name='datasalud',
            name='f_leidacampo',
        ),
        migrations.RemoveField(
            model_name='datasalud',
            name='h_enviadanube',
        ),
        migrations.RemoveField(
            model_name='datasalud',
            name='h_leidacampo',
        ),
    ]
