# Generated by Django 4.2.4 on 2024-01-24 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistaTablas', '0002_remove_datasalud_f_enviadanube_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasalud',
            name='fh_escrituranube',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='datasalud',
            name='fh_lecturamaquina',
            field=models.DateTimeField(null=True),
        ),
    ]
